### ISSUE TITLE
Sudoku_Solver : Increase performance to solve medium difficulty sudoku

### ISSUE THREAD

**Issue by gamab** [nmaguirre/eiffel-sudoku#100]
For the moment Sudoku_Solver is only able to solve easy Sudoku. We could make it better.
For exemple by checking if a value is present in right column upper square and left column lower square but not in the middle column middle square we can guess that this value must be in middle square middle column. See photo for explanations.
![sudoku_technique1](https://f.cloud.github.com/assets/5232696/1127154/e70dc82e-1b32-11e3-8933-e61fd6f022f3.png)
This method could help us to solve medium difficulty sudoku.

**Comment by jucom** [comment]
Tried on a hard one and it worked, hence done in : c198489
