### ISSUE TITLE
Sudoku_Solver : Increase performance to solve hard sudoku

### ISSUE THREAD

**Issue by gamab** [nmaguirre/eiffel-sudoku#101]
We could implement in Sudoku_Solver procedure able to make a guess when we are stuck during the solving process.
This could be done by taking the postit with the lowest number of possible values and pick one of the possible values he has. We save the model before making the guess and we come back if the guess was not a good one.
I think there are other solutions, probably using recursivity, but none comes to my mind right now.

**Comment by jucom** [comment]
I did not implement decision taking but i solved a hard one thanks to c198489
