### ISSUE TITLE
Fixed cells are not highlighted with respect to editable cells

### ISSUE THREAD

**Issue by nmaguirre** [nmaguirre/eiffel-sudoku#108]
Fixed cells (those assigned a fixed value at game initialisation) are not highlighted with respect to other, editable, cells. Thus, a user, after filling in various cells, cannot easily see which cells are editable and which are not, to progress (maybe backtracking) in solving a board.

Cells with filled values must be appropriately highlighted, for user convenience.

**Comment by federf** [comment]
We have a problem with the background of the fixed cells, that when we press backspace button in the keyboard, the background color changes to the default color. I think that we can fix the problem by disabling the backspace button over the fixed cells.

**Comment by federf** [comment]
Solved
