### ISSUE TITLE
Different skins 

### ISSUE THREAD

**Issue by gcoria** [nmaguirre/eiffel-sudoku#111]
The program  should allow diferent themes

**Comment by cesarcorne** [comment]
e4c1e24 in this version i made an abstract class to model the skins

**Comment by gcoria** [comment]
9a9090a added a button box for skin selection

**Comment by gcoria** [comment]
de3eded added a new skin,i don't know how to change the color from the menu bar and it's not linked with the skin button

**Comment by FRaverta** [comment]
301f6f9 added a factory method and link button skin_1 and skin_2 we need solve de view of skins, change colors for example. Please help me with it.

**Comment by mpolitano** [comment]
36e8391

**Comment by FRaverta** [comment]
Well, We have some problems with the skins, but it should be reported as a bug. Maybe we implement a other skins with images or maybe we can finish this issue here, What do you think about it?

**Comment by gcoria** [comment]
i think we should close the issue

**Comment by FRaverta** [comment]
Well, ok thanks all for theirs opinions.
