### ISSUE TITLE
get_hint() function

### ISSUE THREAD

**Issue by teclilla** [nmaguirre/eiffel-sudoku#115]
this function return a value of the solved sudoku (that means the sudoku_board complete) which is not on the sudoku of the game player.
We need to add 1 to our hint_conter (integer)

require: counter_valid
ensure: hint_counter -= 1

**Comment by pmarconi** [comment]
https://github.com/nmaguirre/eiffel-sudoku/commit/7e820ee10a92ba8edb4f535818034f634c04a8ed
