### ISSUE TITLE
Contract violation occurred while try solve the board twice.

### ISSUE THREAD

**Issue by jlgasparrini** [nmaguirre/eiffel-sudoku#121]

**Comment by jlgasparrini** [comment]
DONE!

**Comment by jlgasparrini** [comment]
CLARIFICATION!
Contract violation occurs because the solver does not work properly (i.e., solving a valid board don't ensures my new board is valid). Maybe this problem should be fixed by artificial intelligence team.

**Comment by teclilla** [comment]
Dude... not!  jk :P 
we don't do use of that class thus we can't guarantee that it's working correctly.
For more information checkout our milestone and our issues.
:D
