### ISSUE TITLE
TOP_FIVE: add_player_to_top_five 

### ISSUE THREAD

**Issue by jucom** [nmaguirre/eiffel-sudoku#127]
each a player who won a sudoku and have a score higher than the last one of the player of the top five, is add to the board at the last spot.

**Comment by gamab** [comment]
We need to prevent user to put a TOP_FIVE_PLAYER as he wants to, therefore we need to undefine put inherited from ARRAY[G]. And create this function.
We could also redefine put so that it calls this function.

**Comment by jucom** [comment]
did it in 785c421.
Need to uncomment sort_by_score when the function will be ready
