### ISSUE TITLE
SAVE_AND_LOAD : Set sudoku_board as storable

### ISSUE THREAD

**Issue by gamab** [nmaguirre/eiffel-sudoku#131]

**Comment by mdonatti** [comment]
SAVE_AND_LOAD : Class to save (or load) a game file, lack the time.
6b6caf4

**Comment by gamab** [comment]
We will have to check if to store SAVE_AND_LOAD we need SUDOKU_BOARD as STORABLE like it happens in JAVA.

**Comment by mdonatti** [comment]
fixed save_and_load -> 4c351c7
