### ISSUE TITLE
Missing implementation GUI/MAIN_WINDOW/request_about_hint

### ISSUE THREAD

**Issue by FRaverta** [nmaguirre/eiffel-sudoku#147]
GUI/MAIN_WINDOW/request_about_hint need a implementation, I don't know if we have a method that perform the logic hint for call its.

**Comment by federf** [comment]
i think this issue does not belong to the GUI milestone

**Comment by FRaverta** [comment]
I link gui with controller and IA. Our sudoku can give hint. I solve it at:
ee7a275
