### ISSUE TITLE
Clock implementation

### ISSUE THREAD

**Issue by FRaverta** [nmaguirre/eiffel-sudoku#184]
We need a clock. Naza says: We can count the time with system time, and in our Window only refresh the time when user updates the board.
It issue is solve the logic problem about clock. We should solve the time calculate and update the gui and give information to puntuation.

**Comment by gamab** [comment]
Hey would you have an answer for #204 ?

**Comment by FRaverta** [comment]
I create a class that perform a timer. We only use it. In my opinion, we can create an object:timer in sudoku_board. Then controller drive it adequately.
