### ISSUE TITLE
GUI multiplayer feature

### ISSUE THREAD

**Issue by javierocejo** [nmaguirre/eiffel-sudoku#213]
We need to have a sort of pop up window when a user clicks on muliplayer. This window must offer the user the choice of being a server or being a client (It could be done simply by having a window with 2 buttons). In case the user selects the option of being a client, it would be necessary to fire another pop up window in which the user who chose being a client can submit the server ip in order to connect; this could be done by showing a text field to write an ip and a submit button to submit this ip.

**Comment by federf** [comment]
a08fcd1 Done
