### ISSUE TITLE
The view allows to insert characters

### ISSUE THREAD

**Issue by jlgasparrini** [nmaguirre/eiffel-sudoku#22]

**Comment by gamab** [comment]
I manage to check if what was inserted in the cell box was a character or an integer. But when I ask to set or unset the cell value logically the program fails.
For the moment I update the procedures I did for controlling, but it simply shows what is inside the cell box, doesn't change SUDOKU_BOARD like it should

**Comment by gamab** [comment]
I think board is not initialated
