### ISSUE TITLE
SINGLE_PLAYER_STATE : need to implement a function is_equal

### ISSUE THREAD

**Issue by gamab** [nmaguirre/eiffel-sudoku#232]
For the tests in SAVE_AND_LOAD we need to check if the game we loaded is equal to the game we saved. A simple "=" just check references and therefore doesn't check if objects are equals in value, which is what we need in SAVE_AND_LOAD_TEST.

**Comment by gamab** [comment]
Maybe the function I did in e94836c can help you. I did it very quickly because I thought it would be better if you'd done it in S_P_S.

**Comment by javierocejo** [comment]
Thank you for the guidelines, i'm on it.

**Comment by javierocejo** [comment]
Task Completed!

Best,
Javier.
