### ISSUE TITLE
We need add some methods for set a cell settable feature, 

### ISSUE THREAD

**Issue by cesarcorne** [nmaguirre/eiffel-sudoku#247]
We need to modify make in SUDOKU_AI and add some features:  one_cell_not_settable(row,col: INTEGER) 
 cell_not_settable
 in SINGLE_PLAYER_STATE:
   hint_not_settable(row,col: INTEGER)
in SUDOKU_BOARD:
  define_not_settable(row,col:INTEGER)

I did this and you can see it in branch cesar
Are you agree if i do a push???

**Comment by cesarcorne** [comment]
@pmarconi  @dastorga

**Comment by cesarcorne** [comment]
@malvarez22

**Comment by pmarconi** [comment]
yes, we are agree, do it if you want

**Comment by cesarcorne** [comment]
made in a8d19bd version
