### ISSUE TITLE
Button "New.." in "File" option, not reset the board.

### ISSUE THREAD

**Issue by jlgasparrini** [nmaguirre/eiffel-sudoku#25]

**Comment by gamab** [comment]
We need a function empty_grill capable of resetting the gui board.
Or, which would be even better, we could make a function capable of setting the gui values from the logical ones (Sudoku_Board's ones). This way we could initialise Sudoku_Board and automatically change gui's values.

**Comment by gamab** [comment]
Attention seems pretty similar to #55 !

**Comment by FRaverta** [comment]
New button reset board. If you want that new make a new board with value, only change the contructor used in request new method implementation.
26310d4
