### ISSUE TITLE
GUI - Missing separators between blocks

### ISSUE THREAD

**Issue by gamab** [nmaguirre/eiffel-sudoku#35]
Normally, blocks of 3x3 are separated more clearly from the others.
We should increase the gap between those blocks or insert a black line if possible.

**Comment by federf** [comment]
I think we can use EV_SEPARATOR class, but i'm not sure if it will solve the problem, its just an idea

**Comment by mdonatti** [comment]
proposal: change the background of cells by block

commit : 2f47b5f
