### ISSUE TITLE
Selection of levels to play

### ISSUE THREAD

**Issue by teclilla** [nmaguirre/eiffel-sudoku#54]
It would be nice if we have the option select level on file/new --> n' then pop up a new window with select level option..
<< file/new/select level >>

**Comment by gcoria** [comment]
I solved it in: 
cd7e8c4

Note: I think that We don't have a good policy of game levels. We only create board in the next form:
-> Hard: 30 clues
->Medium: 32 clues
->Easy: 37 clues
