### ISSUE TITLE
Need to forbid modification of initials values

### ISSUE THREAD

**Issue by gamab** [nmaguirre/eiffel-sudoku#68]
We need to forbid modification of initials values. When we make the board, we should not allow user to be able to modify initial values.

**Comment by FRaverta** [comment]
I upgrade an implementation that forbid this change. I had that do change in some methods an implements others, also I create a new atribute in SUDOKU_CELL called settable, this atribute is false when the cell is create for make_with_random (SUDOKU_BOARD)

b243bfa
