### ISSUE TITLE
Easy_Bug : Cell_Text_Field Unset : generate infinite loop

### ISSUE THREAD

**Issue by gamab** [nmaguirre/eiffel-sudoku#70]
In unset we use current.set_text(" ") but ' ' is a character therefore in control text we call unset which once again set the text of the cell to ' ' which therefore in control text call unset...

Instead of current.set_text(" ") we should use current.remove_text

**Comment by jucom** [comment]
I've replaced current.set_text(" ") by current.remove_text in c6b9069
