### ISSUE TITLE
New Game Problem

### ISSUE THREAD

**Issue by federf** [nmaguirre/eiffel-sudoku#72]
Option "New" in "File" Menu shows everytime the same game

**Comment by gamab** [comment]
What we can do is generate already made sudoku that we took from a website.

**Comment by federf** [comment]
i think that we can solve the problem by setting a new seed for the random values generator

**Comment by federf** [comment]
solved

**Comment by cesarcorne** [comment]
done

**Comment by cesarcorne** [comment]
done
