### ISSUE TITLE
Make_With_Random_Value : Generate impossible to solve boards

### ISSUE THREAD

**Issue by gamab** [nmaguirre/eiffel-sudoku#87]
![sudoku_erreur](https://f.cloud.github.com/assets/5232696/1093000/89bda322-1693-11e3-94cb-eb158196cfbf.png)
I was trying to have some fun but could not :-( 
See the board I uploaded I tried to put a one in the selected column but I can't because there are ones in both the middle top and middle bottom squares...

**Comment by nmaguirre** [comment]
Nice issue. Board creation should check board solvability. Class BOARD should have a is_solvable routine. 

Check this for ideas:

http://stackoverflow.com/questions/6924216/how-to-generate-sudoku-boards-with-unique-solutions

**Comment by jucom** [comment]
We could fill all the cells of the board so we know it can be solve and then delete some of the values.
And the more we delete values the harder it gets.

**Comment by jlgasparrini** [comment]
The feature make_with_random_values isn't a functionality of SUDOKU_BOARD. This now is integrated into SUDOKU_AI!!
This issue is finished!
