### ISSUE TITLE
Red Painting decision should be made in Controller, don't you think?

### ISSUE THREAD

**Issue by gamab** [nmaguirre/eiffel-sudoku#90]
It is the Controller's decision to paint a cell in red or not. Not the GUI, we discussed it in class, and since it is in the wiki I think we should make changes.

**Comment by gamab** [comment]
Ok done in version 91e6121, I just commented the functions I copied in case someone didn't like the changes and really wanted to come back to previous version, where the GUI was in charge of controlling insertion.

**Comment by nmaguirre** [comment]
This kind of stuff should be managed using version control and tags, so we don't need to maintain copies of previous implementations. If in doubt, keep old code indicating it's obsolete (Eiffel supports this nicely).

**Comment by gamab** [comment]
Ok, I really don't know how to do this, but it seems a lot better than what I did !
I will have to learn how to manage versions and tags hence.

**Comment by gamab** [comment]
I did a version 0.2 and set as obsolete previous version of copied functions and procedures.
